services:
  tomcat-tlm-neu:
    container_name: tomcat-tlm-neu
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: tomcat
      args:
        MYSQL_USER: user
        MYSQL_PASSWORD: changeme
        DOMAIN_NAME: http://localhost:8080
    ports:
      - "8080:8080"
  mysql-tlm-neu:
    container_name: mysql-tlm-neu
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ALLOW_EMPTY_PASSWORD=1
      MYSQL_USER: user
      MYSQL_PASSWORD: changeme
      # The variable and first two commands below are equivalent to the `CREATE
      # DATABASE` command on Section 2.3 of the manual.
      MYSQL_DATABASE: tsl-noneu
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      # Needed because `migration-script.sql` creates lower case table names
      # and the Java code uses upper case table names.
      - --lower_case_table_names=1
      # Disables deprecation warning from MySQL.
      - --explicit_defaults_for_timestamp=1
  caddy-tlm-neu:
    container_name: caddy-tlm-neu
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: caddy
      args:
        DOMAIN_NAME: http://localhost:80
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
